name: Generate Javadoc

permissions:
  contents: write

on: 
  pull_request:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Javadoc
        run: gradle javadoc
        shell: bash

      - name: Cleanup Javadocs branch
        run: find PATH -maxdepth 1 -type f -delete
        shell: bash
      
      - name: More cleanup
        run: rm -rf gradle scripts src vendordeps .github .vscode
        shell: bash
      
      - name: Publish javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: javadocs
          publish_dir: build/docs/javadoc
          destination_dir: docs/${{ github.head_ref || github.ref_name }}
          force_orphan: true
